version: "3"
services:
  postgres:
    image: postgres
    container_name: postgres_db
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/posgresql/data
  django:
    container_name: django_app
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - .:/usr/src/app
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - postgres
volumes:
  pgdata:
