# Generated by Django 4.0 on 2022-06-01 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authors", "0002_alter_author_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="author",
            name="bio",
            field=models.TextField(blank=True),
        ),
    ]
