# Generated by Django 4.0 on 2022-05-31 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0002_remove_book_in_stock_remove_book_price_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="image",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
