# Generated by Django 4.0 on 2022-05-31 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0003_alter_book_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="book",
            old_name="image",
            new_name="cover_image",
        ),
    ]
