# Generated by Django 4.0 on 2022-05-31 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authors", "0002_alter_author_user"),
        ("books", "0004_rename_image_book_cover_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="author",
            field=models.ManyToManyField(to="authors.Author"),
        ),
    ]
