# Generated by Django 4.0 on 2022-06-01 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authors", "0003_author_bio"),
        ("books", "0005_alter_book_author"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="author",
            field=models.ManyToManyField(related_name="authors", to="authors.Author"),
        ),
    ]
