# Generated by Django 4.0 on 2022-06-01 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0006_alter_book_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="isbn",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
