# Generated by Django 4.0 on 2022-06-01 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0007_book_isbn"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="category_image",
            field=models.ImageField(blank=True, upload_to="category_images/"),
        ),
    ]
