# Generated by Django 4.0 on 2022-06-15 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="avatar",
            field=models.TextField(blank=True, null=True),
        ),
    ]
